import type { Metadata } from "next";
import { Jersey_15 } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";
import { WalletProvider } from "./provider/WalletProvider";

const jersey_15 = Jersey_15({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jersey_15.className} antialiased`}>
        <Provider defaultTheme="light">
          <WalletProvider>
            <Toaster />
            <Navbar />
            {children}
          </WalletProvider>
        </Provider>
      </body>
    </html>
  );
}
